# Change baseurl before deploy
baseurl = "http://localhost:1313"
languageCode = "en-us"
paginate = 5
title = "LGTM"

# Theme i18n support
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "LGTM"
    languagedirection = "ltr"
    [languages.en.params]
      disqusshortname = "hugo-theme-stack"
  [languages.ja]
    languageName = "日本語"
    weight = 2
    title = "LGTM"
    languagedirection = "ltr"
    [languages.ja.params]
      disqusshortname = "hugo-theme-stack"

[params]
  description = "A technical knowledge base for multi-lingual people"
  keywords = "software development, product management, documentation, knowledge base"